<Button>:
    font_size:40
    color:1,.1,.2,1
    size_hint: 0.3,0.4

<FloatLayout>:
    Button:
        #pos: 40, 50
        #pos_hint: {"x","y","top","bottom","left","right"}
        pos_hint: {"x":0.2, "top":0.9}
        text: "Kamil"
        background_color: 0.1, 0.2, 0.9, 0.4
    Button:
        id: btn
        pos_hint: {"x":.1, "y":0}
        text: "Mariusz" if btn.state == "normal" else "Ania"
        background_color: 0.1, 0.2, 0.9, 0.4
